### ISSUE TITLE
Cannot use new/different activation function

### ISSUE THREAD

**Issue by Mithrandir2k18** [paul-krug/pytorch-tcn#20]
I want to use [SiLu](https://pytorch.org/docs/stable/generated/torch.nn.SiLU.html) as the activation function, but I keep getting errors from the `check_activation_arg` function when I pass the class
```
ValueError:
            The argument 'activation' must either be a valid string or
            a torch.nn.Module object, but <class '__main__.SiLU'> was passed,
            which is of type <class 'type'>.
```

and when I pass it as an object it throws this error  

```
    tcn_model = TCN(**model_hyperparams)
 pytorch_tcn/tcn.py", line 530, in __init__
    TemporalBlock(
 /pytorch_tcn/tcn.py", line 257, in __init__
    self.activation1 = self.activation()
                       ^^^^^^^^^^^^^^^^^
 /torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 /torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SiLU.forward() missing 1 required positional argument: 'input'
```

I'm using "pytorch-tcn>=1.2.1", and python 3.12.6.

Right now I'm passing an instance of this wrapper-class as a workaround:

```python
class SiLU(torch.nn.Module):
    def __call__(self, *args, **kwargs):
        return torch.nn.SiLU()
```

**Comment by Mithrandir2k18** [comment]
I'm reasonably certain that the intent was for this [line](https://github.com/paul-krug/pytorch-tcn/blob/b03319c1c90f7a5546395debd0053edbf6e47e7d/pytorch_tcn/tcn.py#L64C1-L64C50):

```python
        ...
    elif not isinstance( activation, nn.Module ):
        ...
```

to be this instead:

```python
        ...
    elif not isinstance(activation(), nn.Module ):
        ...
```

To actually compare if the given argument produces an instance of nn.Module.

**Comment by paul-krug** [comment]
Thank you for the report! You are right, this looks like a bug. I will fix this in an upcomming update within the next few days.
